"""add gap_analysis_data to analyses

Revision ID: 241a0f0ebe24
Revises: ea3676286704
Create Date: 2026-09-08 10:42:10.051911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '241a0f0ebe24'
down_revision: Union[str, Sequence[str], None] = 'ea3676286704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('gap_analysis_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'gap_analysis_data')
    # ### end Alembic commands ###
